-- ============================================================================
-- MARKET VIEWS - Consumer-facing market data views
-- ============================================================================

-- Latest prices per symbol (most recent trading day)
CREATE OR REPLACE SECURE VIEW CORE.V_LATEST_PRICES AS
SELECT
    mp.SYMBOL,
    mp.EXCHANGE,
    mp.TRADE_DATE,
    mp.OPEN_PRICE,
    mp.HIGH_PRICE,
    mp.LOW_PRICE,
    mp.CLOSE_PRICE,
    mp.ADJ_CLOSE,
    mp.VOLUME,
    mp.CURRENCY
FROM CORE.MARKET_PRICES mp
WHERE mp.TRADE_DATE = (
    SELECT MAX(TRADE_DATE) FROM CORE.MARKET_PRICES WHERE SYMBOL = mp.SYMBOL
);

-- Price history with moving averages
CREATE OR REPLACE SECURE VIEW CORE.V_PRICE_HISTORY AS
SELECT
    SYMBOL,
    TRADE_DATE,
    CLOSE_PRICE,
    ADJ_CLOSE,
    VOLUME,
    AVG(ADJ_CLOSE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE ROWS 19 PRECEDING) AS SMA_20,
    AVG(ADJ_CLOSE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE ROWS 49 PRECEDING) AS SMA_50,
    AVG(ADJ_CLOSE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE ROWS 199 PRECEDING) AS SMA_200,
    (ADJ_CLOSE - LAG(ADJ_CLOSE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE))
        / NULLIF(LAG(ADJ_CLOSE) OVER (PARTITION BY SYMBOL ORDER BY TRADE_DATE), 0) AS DAILY_RETURN
FROM CORE.MARKET_PRICES;

-- Company overview (latest quarter)
CREATE OR REPLACE SECURE VIEW CORE.V_COMPANY_OVERVIEW AS
SELECT
    cf.SYMBOL,
    cf.COMPANY_NAME,
    cf.SECTOR,
    cf.INDUSTRY,
    cf.REVENUE,
    cf.NET_INCOME,
    cf.EPS,
    cf.PE_RATIO,
    cf.MARKET_CAP,
    cf.FISCAL_YEAR,
    cf.FISCAL_QUARTER
FROM CORE.COMPANY_FUNDAMENTALS cf
INNER JOIN (
    SELECT SYMBOL, MAX(FISCAL_YEAR * 10 + FISCAL_QUARTER) AS MAX_YQ
    FROM CORE.COMPANY_FUNDAMENTALS
    GROUP BY SYMBOL
) latest ON cf.SYMBOL = latest.SYMBOL
    AND (cf.FISCAL_YEAR * 10 + cf.FISCAL_QUARTER) = latest.MAX_YQ;

-- Sector performance summary
CREATE OR REPLACE SECURE VIEW CORE.V_SECTOR_SUMMARY AS
SELECT
    cf.SECTOR,
    COUNT(DISTINCT cf.SYMBOL) AS NUM_COMPANIES,
    SUM(cf.MARKET_CAP) AS TOTAL_MARKET_CAP,
    AVG(cf.PE_RATIO) AS AVG_PE_RATIO,
    AVG(cf.REVENUE) AS AVG_REVENUE,
    AVG(cf.EPS) AS AVG_EPS
FROM CORE.COMPANY_FUNDAMENTALS cf
WHERE cf.FISCAL_YEAR = YEAR(CURRENT_DATE())
    AND cf.SECTOR IS NOT NULL
GROUP BY cf.SECTOR;

-- Grant view access
GRANT SELECT ON VIEW CORE.V_LATEST_PRICES TO APPLICATION ROLE APP_VIEWER;
GRANT SELECT ON VIEW CORE.V_PRICE_HISTORY TO APPLICATION ROLE APP_VIEWER;
GRANT SELECT ON VIEW CORE.V_COMPANY_OVERVIEW TO APPLICATION ROLE APP_VIEWER;
GRANT SELECT ON VIEW CORE.V_SECTOR_SUMMARY TO APPLICATION ROLE APP_VIEWER;

GRANT SELECT ON VIEW CORE.V_LATEST_PRICES TO APPLICATION ROLE APP_ANALYST;
GRANT SELECT ON VIEW CORE.V_PRICE_HISTORY TO APPLICATION ROLE APP_ANALYST;
GRANT SELECT ON VIEW CORE.V_COMPANY_OVERVIEW TO APPLICATION ROLE APP_ANALYST;
GRANT SELECT ON VIEW CORE.V_SECTOR_SUMMARY TO APPLICATION ROLE APP_ANALYST;

GRANT SELECT ON VIEW CORE.V_LATEST_PRICES TO APPLICATION ROLE APP_ADMIN;
GRANT SELECT ON VIEW CORE.V_PRICE_HISTORY TO APPLICATION ROLE APP_ADMIN;
GRANT SELECT ON VIEW CORE.V_COMPANY_OVERVIEW TO APPLICATION ROLE APP_ADMIN;
GRANT SELECT ON VIEW CORE.V_SECTOR_SUMMARY TO APPLICATION ROLE APP_ADMIN;
