-- ============================================================================
-- RISK VIEWS - Risk analytics views
-- ============================================================================

-- Latest risk metrics per symbol
CREATE OR REPLACE SECURE VIEW CORE.V_RISK_DASHBOARD AS
SELECT
    rm.SYMBOL,
    rm.CALC_DATE,
    rm.VOLATILITY_30D,
    rm.VOLATILITY_90D,
    rm.SHARPE_RATIO,
    rm.BETA,
    rm.VAR_95,
    rm.MAX_DRAWDOWN,
    rm.SORTINO_RATIO,
    cf.SECTOR,
    cf.INDUSTRY
FROM CORE.RISK_METRICS rm
LEFT JOIN CORE.COMPANY_FUNDAMENTALS cf
    ON rm.SYMBOL = cf.SYMBOL
    AND cf.FISCAL_YEAR = YEAR(CURRENT_DATE())
    AND cf.FISCAL_QUARTER = (SELECT MAX(FISCAL_QUARTER) FROM CORE.COMPANY_FUNDAMENTALS
                             WHERE SYMBOL = cf.SYMBOL AND FISCAL_YEAR = YEAR(CURRENT_DATE()))
WHERE rm.CALC_DATE = (SELECT MAX(CALC_DATE) FROM CORE.RISK_METRICS WHERE SYMBOL = rm.SYMBOL);

-- Risk heatmap view (sector-level aggregation)
CREATE OR REPLACE SECURE VIEW CORE.V_SECTOR_RISK AS
SELECT
    cf.SECTOR,
    AVG(rm.VOLATILITY_30D) AS AVG_VOLATILITY_30D,
    AVG(rm.BETA) AS AVG_BETA,
    AVG(rm.SHARPE_RATIO) AS AVG_SHARPE_RATIO,
    AVG(rm.VAR_95) AS AVG_VAR_95,
    AVG(rm.MAX_DRAWDOWN) AS AVG_MAX_DRAWDOWN,
    COUNT(DISTINCT rm.SYMBOL) AS NUM_SYMBOLS
FROM CORE.RISK_METRICS rm
INNER JOIN CORE.COMPANY_FUNDAMENTALS cf ON rm.SYMBOL = cf.SYMBOL
WHERE rm.CALC_DATE = (SELECT MAX(CALC_DATE) FROM CORE.RISK_METRICS)
    AND cf.SECTOR IS NOT NULL
GROUP BY cf.SECTOR;

-- High-risk alert view
CREATE OR REPLACE SECURE VIEW CORE.V_HIGH_RISK_ALERTS AS
SELECT
    rm.SYMBOL,
    rm.CALC_DATE,
    rm.VOLATILITY_30D,
    rm.VAR_95,
    rm.MAX_DRAWDOWN,
    CASE
        WHEN rm.VOLATILITY_30D > 0.5 THEN 'EXTREME'
        WHEN rm.VOLATILITY_30D > 0.3 THEN 'HIGH'
        WHEN rm.VOLATILITY_30D > 0.15 THEN 'MODERATE'
        ELSE 'LOW'
    END AS RISK_LEVEL
FROM CORE.RISK_METRICS rm
WHERE rm.CALC_DATE = (SELECT MAX(CALC_DATE) FROM CORE.RISK_METRICS WHERE SYMBOL = rm.SYMBOL)
    AND rm.VOLATILITY_30D > 0.15;

-- Grant view access
GRANT SELECT ON VIEW CORE.V_RISK_DASHBOARD TO APPLICATION ROLE APP_ANALYST;
GRANT SELECT ON VIEW CORE.V_SECTOR_RISK TO APPLICATION ROLE APP_ANALYST;
GRANT SELECT ON VIEW CORE.V_HIGH_RISK_ALERTS TO APPLICATION ROLE APP_ANALYST;

GRANT SELECT ON VIEW CORE.V_RISK_DASHBOARD TO APPLICATION ROLE APP_ADMIN;
GRANT SELECT ON VIEW CORE.V_SECTOR_RISK TO APPLICATION ROLE APP_ADMIN;
GRANT SELECT ON VIEW CORE.V_HIGH_RISK_ALERTS TO APPLICATION ROLE APP_ADMIN;
