-- ============================================================================
-- ANALYTICS SCHEMA - Derived computations and consumer-facing analytics
-- ============================================================================

-- Portfolio analysis results (per consumer)
CREATE TABLE IF NOT EXISTS ANALYTICS.PORTFOLIO_ANALYSIS (
    ANALYSIS_ID     NUMBER AUTOINCREMENT,
    PORTFOLIO_NAME  VARCHAR(200),
    SYMBOL          VARCHAR(20),
    WEIGHT          NUMBER(8,4),
    EXPECTED_RETURN NUMBER(12,6),
    CONTRIBUTION_TO_RISK NUMBER(12,6),
    ANALYSIS_DATE   DATE            DEFAULT CURRENT_DATE(),
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- Screener results (cached)
CREATE TABLE IF NOT EXISTS ANALYTICS.SCREENER_RESULTS (
    SCREEN_ID       NUMBER AUTOINCREMENT,
    SCREEN_NAME     VARCHAR(200),
    CRITERIA_JSON   VARIANT,
    RESULT_SYMBOLS  ARRAY,
    RESULT_COUNT    INTEGER,
    RUN_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- Correlation matrix cache
CREATE TABLE IF NOT EXISTS ANALYTICS.CORRELATION_CACHE (
    SYMBOL_A        VARCHAR(20),
    SYMBOL_B        VARCHAR(20),
    CORRELATION     NUMBER(12,8),
    WINDOW_DAYS     INTEGER,
    CALC_DATE       DATE            DEFAULT CURRENT_DATE()
);

-- Grant access to analysts
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ANALYTICS TO APPLICATION ROLE APP_ANALYST;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ANALYTICS TO APPLICATION ROLE APP_ADMIN;
