-- ============================================================================
-- CONFIG SCHEMA - Application configuration and state
-- ============================================================================

-- App configuration (tier, refresh settings, etc.)
CREATE TABLE IF NOT EXISTS CONFIG.APP_SETTINGS (
    SETTING_KEY     VARCHAR(100)    NOT NULL,
    SETTING_VALUE   VARCHAR(1000),
    UPDATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY      VARCHAR(200)
);

-- Insert default settings
MERGE INTO CONFIG.APP_SETTINGS AS target
USING (
    SELECT * FROM VALUES
        ('DATA_TIER', 'STANDARD', CURRENT_TIMESTAMP(), 'SYSTEM'),
        ('REFRESH_INTERVAL_MINUTES', '30', CURRENT_TIMESTAMP(), 'SYSTEM'),
        ('MAX_SYMBOLS', '5000', CURRENT_TIMESTAMP(), 'SYSTEM'),
        ('ENABLE_RISK_ANALYTICS', 'TRUE', CURRENT_TIMESTAMP(), 'SYSTEM'),
        ('HEALTH_CHECK_ENABLED', 'TRUE', CURRENT_TIMESTAMP(), 'SYSTEM')
    AS s(SETTING_KEY, SETTING_VALUE, UPDATED_AT, UPDATED_BY)
) AS source
ON target.SETTING_KEY = source.SETTING_KEY
WHEN NOT MATCHED THEN
    INSERT (SETTING_KEY, SETTING_VALUE, UPDATED_AT, UPDATED_BY)
    VALUES (source.SETTING_KEY, source.SETTING_VALUE, source.UPDATED_AT, source.UPDATED_BY);

-- Audit log for tracking app operations
CREATE TABLE IF NOT EXISTS CONFIG.AUDIT_LOG (
    LOG_ID          NUMBER AUTOINCREMENT,
    EVENT_TYPE      VARCHAR(50)     NOT NULL,
    EVENT_DETAIL    VARCHAR(2000),
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY      VARCHAR(200)    DEFAULT CURRENT_USER()
);

-- Reference tracking for consumer-bound objects
CREATE TABLE IF NOT EXISTS CONFIG.BOUND_REFERENCES (
    REFERENCE_NAME  VARCHAR(100)    NOT NULL,
    OBJECT_NAME     VARCHAR(500),
    BOUND_AT        TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- Grant access
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA CONFIG TO APPLICATION ROLE APP_ADMIN;
