-- ============================================================================
-- INTEGRATION TEST: Fresh Install Validation
-- Run after: snow app run
-- Validates: All objects created, roles exist, permissions correct
-- ============================================================================

-- T1: Core schema exists and has expected tables
SELECT 'T1_CORE_TABLES' AS TEST,
    CASE WHEN COUNT(*) >= 4 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CORE' AND TABLE_TYPE = 'BASE TABLE';

-- T2: Config schema exists with settings
SELECT 'T2_CONFIG_SCHEMA' AS TEST,
    CASE WHEN COUNT(*) >= 1 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'CONFIG';

-- T3: Analytics schema exists
SELECT 'T3_ANALYTICS_SCHEMA' AS TEST,
    CASE WHEN COUNT(*) >= 1 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ANALYTICS';

-- T4: Secure views created
SELECT 'T4_SECURE_VIEWS' AS TEST,
    CASE WHEN COUNT(*) >= 7 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.INFORMATION_SCHEMA.VIEWS
WHERE TABLE_SCHEMA = 'CORE';

-- T5: Procedures created
SELECT 'T5_PROCEDURES' AS TEST,
    CASE WHEN COUNT(*) >= 5 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA IN ('CORE', 'ANALYTICS');

-- T6: Streamlit app created
SELECT 'T6_STREAMLIT' AS TEST,
    CASE WHEN COUNT(*) = 1 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.INFORMATION_SCHEMA.STREAMLITS
WHERE STREAMLIT_SCHEMA = 'CORE' AND STREAMLIT_NAME = 'DASHBOARD';

-- T7: Default config settings populated
SELECT 'T7_DEFAULT_CONFIG' AS TEST,
    CASE WHEN COUNT(*) >= 5 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.CONFIG.APP_SETTINGS;

-- T8: Health check procedure runs successfully
CALL FINDATA_APP.CORE.HEALTH_CHECK();
