-- ============================================================================
-- INTEGRATION TEST: Upgrade Path Validation
-- Run: Install v(N-1), insert test data, upgrade to v(N), verify data persists
-- ============================================================================

-- Pre-upgrade: Insert test data into core tables
INSERT INTO FINDATA_APP.CORE.MARKET_PRICES
    (SYMBOL, EXCHANGE, TRADE_DATE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, ADJ_CLOSE, VOLUME)
VALUES
    ('TEST1', 'NYSE', '2026-01-01', 100.00, 105.00, 99.00, 104.00, 104.00, 1000000),
    ('TEST2', 'NASDAQ', '2026-01-01', 50.00, 52.00, 49.00, 51.00, 51.00, 500000);

INSERT INTO FINDATA_APP.CONFIG.APP_SETTINGS (SETTING_KEY, SETTING_VALUE, UPDATED_BY)
VALUES ('UPGRADE_TEST_KEY', 'pre_upgrade_value', 'TEST');

-- Record pre-upgrade counts
SELECT 'PRE_UPGRADE_MARKET_PRICES' AS CHECKPOINT, COUNT(*) AS ROW_COUNT
FROM FINDATA_APP.CORE.MARKET_PRICES;

SELECT 'PRE_UPGRADE_CONFIG' AS CHECKPOINT, COUNT(*) AS ROW_COUNT
FROM FINDATA_APP.CONFIG.APP_SETTINGS;

-- ============ UPGRADE HAPPENS HERE (snow app run) ============

-- Post-upgrade: Verify data persists
SELECT 'T1_DATA_PERSISTENCE' AS TEST,
    CASE WHEN COUNT(*) >= 2 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.CORE.MARKET_PRICES
WHERE SYMBOL IN ('TEST1', 'TEST2');

-- Verify config persists
SELECT 'T2_CONFIG_PERSISTENCE' AS TEST,
    CASE WHEN SETTING_VALUE = 'pre_upgrade_value' THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.CONFIG.APP_SETTINGS
WHERE SETTING_KEY = 'UPGRADE_TEST_KEY';

-- Verify new objects exist (if version added new objects)
SELECT 'T3_SCHEMA_INTACT' AS TEST,
    CASE WHEN COUNT(*) >= 3 THEN 'PASS' ELSE 'FAIL' END AS RESULT
FROM FINDATA_APP.INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME IN ('CORE', 'CONFIG', 'ANALYTICS');

-- Verify procedures still work
CALL FINDATA_APP.CORE.HEALTH_CHECK();
SELECT 'T4_PROCEDURES_INTACT' AS TEST, 'PASS' AS RESULT;

-- Cleanup test data
DELETE FROM FINDATA_APP.CORE.MARKET_PRICES WHERE SYMBOL IN ('TEST1', 'TEST2');
DELETE FROM FINDATA_APP.CONFIG.APP_SETTINGS WHERE SETTING_KEY = 'UPGRADE_TEST_KEY';
