-- ============================================================================
-- FINDATA NATIVE APP - Main Setup Script
-- Orchestrates all modular scripts for install and upgrade
-- ============================================================================

-- Create application roles
CREATE APPLICATION ROLE IF NOT EXISTS APP_ADMIN;
CREATE APPLICATION ROLE IF NOT EXISTS APP_ANALYST;
CREATE APPLICATION ROLE IF NOT EXISTS APP_VIEWER;

GRANT APPLICATION ROLE APP_ANALYST TO APPLICATION ROLE APP_ADMIN;
GRANT APPLICATION ROLE APP_VIEWER TO APPLICATION ROLE APP_ANALYST;

-- Create schemas
CREATE OR ALTER VERSIONED SCHEMA CORE;
CREATE SCHEMA IF NOT EXISTS CONFIG;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Grant schema usage
GRANT USAGE ON SCHEMA CORE TO APPLICATION ROLE APP_VIEWER;
GRANT USAGE ON SCHEMA CORE TO APPLICATION ROLE APP_ANALYST;
GRANT USAGE ON SCHEMA CORE TO APPLICATION ROLE APP_ADMIN;
GRANT USAGE ON SCHEMA ANALYTICS TO APPLICATION ROLE APP_ANALYST;
GRANT USAGE ON SCHEMA ANALYTICS TO APPLICATION ROLE APP_ADMIN;
GRANT USAGE ON SCHEMA CONFIG TO APPLICATION ROLE APP_ADMIN;

-- Execute modular scripts
EXECUTE IMMEDIATE FROM '/scripts/schemas/core_schema.sql';
EXECUTE IMMEDIATE FROM '/scripts/schemas/config_schema.sql';
EXECUTE IMMEDIATE FROM '/scripts/schemas/analytics_schema.sql';
EXECUTE IMMEDIATE FROM '/scripts/procedures/admin_procs.sql';
EXECUTE IMMEDIATE FROM '/scripts/procedures/analytics_procs.sql';
EXECUTE IMMEDIATE FROM '/scripts/views/market_views.sql';
EXECUTE IMMEDIATE FROM '/scripts/views/risk_views.sql';

-- Create Streamlit app
CREATE OR REPLACE STREAMLIT CORE.DASHBOARD
    FROM '/streamlit'
    MAIN_FILE = '/dashboard.py';

GRANT USAGE ON STREAMLIT CORE.DASHBOARD TO APPLICATION ROLE APP_VIEWER;
GRANT USAGE ON STREAMLIT CORE.DASHBOARD TO APPLICATION ROLE APP_ANALYST;
GRANT USAGE ON STREAMLIT CORE.DASHBOARD TO APPLICATION ROLE APP_ADMIN;

-- Report health on successful setup
CALL SYSTEM$REPORT_HEALTH_STATUS('OK');
