-- ============================================================================
-- ANALYTICS PROCEDURES - Financial computations
-- ============================================================================

-- Calculate returns for a symbol over a date range
CREATE OR REPLACE PROCEDURE ANALYTICS.CALC_RETURNS(
    p_symbol STRING,
    p_start_date DATE,
    p_end_date DATE
)
RETURNS TABLE(TRADE_DATE DATE, DAILY_RETURN FLOAT, CUMULATIVE_RETURN FLOAT)
LANGUAGE SQL
AS
BEGIN
    LET res RESULTSET := (
        SELECT
            TRADE_DATE,
            ((ADJ_CLOSE - LAG(ADJ_CLOSE) OVER (ORDER BY TRADE_DATE))
                / NULLIF(LAG(ADJ_CLOSE) OVER (ORDER BY TRADE_DATE), 0))::FLOAT AS DAILY_RETURN,
            ((ADJ_CLOSE / FIRST_VALUE(ADJ_CLOSE) OVER (ORDER BY TRADE_DATE)) - 1)::FLOAT AS CUMULATIVE_RETURN
        FROM CORE.MARKET_PRICES
        WHERE SYMBOL = :p_symbol
            AND TRADE_DATE BETWEEN :p_start_date AND :p_end_date
        ORDER BY TRADE_DATE
    );
    RETURN TABLE(res);
END;

GRANT USAGE ON PROCEDURE ANALYTICS.CALC_RETURNS(STRING, DATE, DATE)
    TO APPLICATION ROLE APP_ANALYST;
GRANT USAGE ON PROCEDURE ANALYTICS.CALC_RETURNS(STRING, DATE, DATE)
    TO APPLICATION ROLE APP_ADMIN;

-- Calculate correlation between two symbols
CREATE OR REPLACE PROCEDURE ANALYTICS.CALC_CORRELATION(
    p_symbol_a STRING,
    p_symbol_b STRING,
    p_window_days INTEGER
)
RETURNS FLOAT
LANGUAGE SQL
AS
BEGIN
    LET correlation FLOAT := 0;

    SELECT CORR(a.DAILY_RETURN, b.DAILY_RETURN) INTO :correlation
    FROM (
        SELECT TRADE_DATE,
               (ADJ_CLOSE - LAG(ADJ_CLOSE) OVER (ORDER BY TRADE_DATE))
                   / NULLIF(LAG(ADJ_CLOSE) OVER (ORDER BY TRADE_DATE), 0) AS DAILY_RETURN
        FROM CORE.MARKET_PRICES
        WHERE SYMBOL = :p_symbol_a
            AND TRADE_DATE >= DATEADD(DAY, -:p_window_days, CURRENT_DATE())
    ) a
    INNER JOIN (
        SELECT TRADE_DATE,
               (ADJ_CLOSE - LAG(ADJ_CLOSE) OVER (ORDER BY TRADE_DATE))
                   / NULLIF(LAG(ADJ_CLOSE) OVER (ORDER BY TRADE_DATE), 0) AS DAILY_RETURN
        FROM CORE.MARKET_PRICES
        WHERE SYMBOL = :p_symbol_b
            AND TRADE_DATE >= DATEADD(DAY, -:p_window_days, CURRENT_DATE())
    ) b ON a.TRADE_DATE = b.TRADE_DATE;

    -- Cache result
    INSERT INTO ANALYTICS.CORRELATION_CACHE (SYMBOL_A, SYMBOL_B, CORRELATION, WINDOW_DAYS)
        VALUES (:p_symbol_a, :p_symbol_b, :correlation, :p_window_days);

    RETURN correlation;
END;

GRANT USAGE ON PROCEDURE ANALYTICS.CALC_CORRELATION(STRING, STRING, INTEGER)
    TO APPLICATION ROLE APP_ANALYST;
GRANT USAGE ON PROCEDURE ANALYTICS.CALC_CORRELATION(STRING, STRING, INTEGER)
    TO APPLICATION ROLE APP_ADMIN;

-- Stock screener: filter by fundamental criteria
CREATE OR REPLACE PROCEDURE ANALYTICS.STOCK_SCREENER(
    p_min_market_cap NUMBER,
    p_max_pe_ratio NUMBER,
    p_sector STRING
)
RETURNS TABLE(SYMBOL VARCHAR, COMPANY_NAME VARCHAR, MARKET_CAP BIGINT, PE_RATIO FLOAT, SECTOR VARCHAR)
LANGUAGE SQL
AS
BEGIN
    LET res RESULTSET := (
        SELECT DISTINCT
            cf.SYMBOL,
            cf.COMPANY_NAME,
            cf.MARKET_CAP::BIGINT AS MARKET_CAP,
            cf.PE_RATIO::FLOAT AS PE_RATIO,
            cf.SECTOR
        FROM CORE.COMPANY_FUNDAMENTALS cf
        WHERE cf.MARKET_CAP >= :p_min_market_cap
            AND (cf.PE_RATIO <= :p_max_pe_ratio OR :p_max_pe_ratio IS NULL)
            AND (cf.SECTOR = :p_sector OR :p_sector IS NULL)
            AND cf.FISCAL_YEAR = YEAR(CURRENT_DATE())
        ORDER BY 3 DESC
    );
    RETURN TABLE(res);
END;

GRANT USAGE ON PROCEDURE ANALYTICS.STOCK_SCREENER(NUMBER, NUMBER, STRING)
    TO APPLICATION ROLE APP_ANALYST;
GRANT USAGE ON PROCEDURE ANALYTICS.STOCK_SCREENER(NUMBER, NUMBER, STRING)
    TO APPLICATION ROLE APP_ADMIN;

-- Portfolio risk summary
CREATE OR REPLACE PROCEDURE ANALYTICS.PORTFOLIO_RISK_SUMMARY(p_symbols ARRAY)
RETURNS TABLE(SYMBOL VARCHAR, VOLATILITY_30D FLOAT, BETA FLOAT, VAR_95 FLOAT, SHARPE_RATIO FLOAT)
LANGUAGE SQL
AS
BEGIN
    LET res RESULTSET := (
        SELECT
            rm.SYMBOL,
            rm.VOLATILITY_30D::FLOAT AS VOLATILITY_30D,
            rm.BETA::FLOAT AS BETA,
            rm.VAR_95::FLOAT AS VAR_95,
            rm.SHARPE_RATIO::FLOAT AS SHARPE_RATIO
        FROM CORE.RISK_METRICS rm
        WHERE rm.SYMBOL IN (SELECT VALUE::STRING FROM TABLE(FLATTEN(:p_symbols)))
            AND rm.CALC_DATE = (SELECT MAX(CALC_DATE) FROM CORE.RISK_METRICS WHERE SYMBOL = rm.SYMBOL)
        ORDER BY rm.SYMBOL
    );
    RETURN TABLE(res);
END;

GRANT USAGE ON PROCEDURE ANALYTICS.PORTFOLIO_RISK_SUMMARY(ARRAY)
    TO APPLICATION ROLE APP_ANALYST;
GRANT USAGE ON PROCEDURE ANALYTICS.PORTFOLIO_RISK_SUMMARY(ARRAY)
    TO APPLICATION ROLE APP_ADMIN;
